# Generated by Django 5.2.9 on 2025-12-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('eligibility', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('min_attendance', models.IntegerField(default=75)),
            ],
        ),
    ]
